[package]
name = "honeyssh"
version = "0.1.0"
authors = ["tatref <tatref@github.com>"]

[dependencies]
thrussh = "0.20"
thrussh-keys = "*"
futures = "0.1"
tokio = "0.1"
env_logger = "0.4"
log = "0.3"
glob = "0.2"

